required = ["github.com/gorilla/websocket"]

[[constraint]]
    name = "github.com/xgfone/go-tools"
    version = "v3.2.0"

[[constraint]]
    name = "github.com/xgfone/miss"
    branch = "master"

[[constraint]]
    name = "github.com/go-redis/redis"
    version = "v6.6.0"

[[constraint]]
    name = "github.com/gorilla/websocket"
    version = "v1.4.0"
